# TODO 'snapcraft register <name>'
name: proton-pass
icon: snap/gui/proton-pass.svg
summary: Proton Pass desktop application.
adopt-info: proton-pass
description: |
  Open-source and secure identity manager.

website: https://proton.me/pass
contact: https://github.com/pedro-avalos/proton-pass-snap/issues
issues: https://github.com/pedro-avalos/proton-pass-snap/issues
source-code: https://github.com/ProtonMail/WebClients

base: core24
grade: stable
confinement: strict
compression: lzo

platforms:
  amd64:

apps:
  proton-pass:
    command: usr/bin/proton-pass --no-sandbox
    desktop: meta/gui/proton-pass.desktop
    extensions:
      - gnome
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
      - browser-support
      - password-manager-service  # TODO: This should probably auto-connect
      - gsettings
      - home
      - removable-media
      - hardware-observe  # NOTE: This seems to allow access to detect security keys...
      - u2f-devices  # TODO: This should probably auto-connect
      - network

parts:
  proton-pass:
    plugin: npm
    source-type: git
    source: https://github.com/ProtonMail/WebClients
    build-snaps:
      - node/20/stable
    build-packages:
      - jq
    override-pull: |
      craftctl default
      craftctl set version=$(jq -r .version < applications/pass-desktop/package.json)
    override-build: |
      yarn install
      yarn build:desktop

      mkdir -p $CRAFT_PART_INSTALL/usr/lib/proton-pass \
        $CRAFT_PART_INSTALL/usr/bin

      cp -r applications/pass-desktop/out/Proton\ Pass-linux-x64/* \
        $CRAFT_PART_INSTALL/usr/lib/proton-pass/

      ln -s ../lib/proton-pass/Proton\ Pass \
        $CRAFT_PART_INSTALL/usr/bin/proton-pass
