name: proton-pass
icon: snap/gui/proton-pass.svg
summary: Proton Pass desktop application.
version: 1.22.1
description: |
  Open-source and secure identity manager.

website: https://proton.me/pass
contact: https://github.com/pedro-avalos/proton-pass-snap/issues
issues: https://github.com/pedro-avalos/proton-pass-snap/issues
source-code: https://github.com/ProtonMail/WebClients

base: core24
grade: stable
confinement: strict
compression: lzo

platforms:
  amd64:

apps:
  proton-pass:
    command: launcher
    desktop: usr/share/applications/proton-pass.desktop
    extensions:
      - gnome
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
      - browser-support
      - password-manager-service
      - gsettings
      - home
      - removable-media
      - hardware-observe
      - u2f-devices
      - network

parts:
  launcher:
    plugin: dump
    source: launcher
    override-build: |
      cp launcher $CRAFT_PART_INSTALL/

  proton-pass:
    plugin: dump
    source-type: deb
    source: https://proton.me/download/PassDesktop/linux/x64/ProtonPass_${SNAPCRAFT_PROJECT_VERSION}.deb
    source-checksum: sha512/8c693d46130c223a4b4eed07eec88f5cbda5971bf7260118d458f21c223e330bace6346e5cbd507fdac09631d33068327fd32e55e54e16ea069cf7a6a7d10b0a
    prime:
      - -usr/lib/proton-pass/chrome-sandbox