name: proton-pass
icon: snap/gui/proton-pass.svg
summary: Proton Pass desktop application.
version: 1.22.0
description: |
  Open-source and secure identity manager.

website: https://proton.me/pass
contact: https://github.com/pedro-avalos/proton-pass-snap/issues
issues: https://github.com/pedro-avalos/proton-pass-snap/issues
source-code: https://github.com/ProtonMail/WebClients

base: core24
grade: stable
confinement: strict
compression: lzo

platforms:
  amd64:

apps:
  proton-pass:
    command: usr/bin/proton-pass --no-sandbox
    desktop: usr/share/applications/proton-pass.desktop
    extensions:
      - gnome
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
      - browser-support
      - password-manager-service
      - gsettings
      - home
      - removable-media
      - hardware-observe  # NOTE: This seems to allow access to detect security keys...
      - u2f-devices  # TODO: This should probably auto-connect
      - network

parts:
  proton-pass:
    plugin: dump
    source-type: deb
    source: https://proton.me/download/PassDesktop/linux/x64/ProtonPass_1.22.0.deb
    source-checksum: sha512/981a9ffa8c2db800cf59f2b863ba24ca4ddfc363b0765beb0eb1aab1b440ff7deb5636e55a9741e6d5ffdd01a7d8431f6ca454ec5bfa1c01abe4c31516885f4f
    prime:
      - -usr/lib/proton-pass/chrome-sandbox